export default [
  //HAND BAGS
  {
    id: 'hb_01',
    prod_section: 'hand bags',
    prod_name: '',
    image: '',
    details: '',
    price: '',
    bulk_price: '',
    discount: '',
    dimensions: '',
    available: '',
  },

  {
    id: 'hb_02',
    prod_section: 'hand bags',
    prod_name: '',
    image: '',
    details: '',
    price: '',
    bulk_price: '',
    discount: '',
    dimensions: '',
    available: '',
  },
  {
    id: 'hb_03',
    prod_section: 'hand bags',
    prod_name: '',
    image: '',
    details: '',
    price: '',
    bulk_price: '',
    discount: '',
    dimensions: '',
    available: '',
  },
  {
    id: 'hb_04',
    prod_section: 'hand bags',
    prod_name: '',
    image: '',
    details: '',
    price: '',
    bulk_price: '',
    discount: '',
    dimensions: '',
    available: '',
  },
  {
    id: 'hb_05',
    prod_section: 'hand bags',
    prod_name: '',
    image: '',
    details: '',
    price: '',
    bulk_price: '',
    discount: '',
    dimensions: '',
    available: '',
  },
  {
    id: 'hb_06',
    prod_section: 'hand bags',
    prod_name: '',
    image: '',
    details: '',
    price: '',
    bulk_price: '',
    discount: '',
    dimensions: '',
    available: '',
  },
  {
    id: 'hb_07',
    prod_section: 'hand bags',
    prod_name: '',
    image: '',
    details: '',
    price: '',
    bulk_price: '',
    discount: '',
    dimensions: '',
    available: '',
  },
  {
    id: 'hb_08',
    prod_section: 'hand bags',
    prod_name: '',
    image: '',
    details: '',
    price: '',
    bulk_price: '',
    discount: '',
    dimensions: '',
    available: '',
  },
  {
    id: 'hb_09',
    prod_section: 'hand bags',
    prod_name: '',
    image: '',
    details: '',
    price: '',
    bulk_price: '',
    discount: '',
    dimensions: '',
    available: '',
  },
  {
    id: 'hb_10',
    prod_section: 'hand bags',
    prod_name: '',
    image: '',
    details: '',
    price: '',
    bulk_price: '',
    discount: '',
    dimensions: '',
    available: '',
  },
  {
    id: 'hb_11',
    prod_section: 'hand bags',
    prod_name: '',
    image: '',
    details: '',
    price: '',
    bulk_price: '',
    discount: '',
    dimensions: '',
    available: '',
  },
  {
    id: 'hb_12',
    prod_section: 'hand bags',
    prod_name: '',
    image: '',
    details: '',
    price: '',
    bulk_price: '',
    discount: '',
    dimensions: '',
    available: '',
  },
]
